### ISSUE TITLE
Run task in a specific thread (or in all threads)

### ISSUE THREAD

**Issue by piula** [renancostab/HPThreadPool#1]
Hello,

I'm using your HPThreadPool and am looking for a way to do some cleanup work when a thread terminates (either because the number of worker threads being decreased or because of the thread pool shutting down). I cannot use the thread's OnTerminate event because (as far as I know) it is being run in the context of the main thread. However, I need to be sure that cleanup is done in the context of the worker thread.

Something like THPThreadPool.OnTerminateWorker would be very handy. Maybe you could give me some advice how to properly add this. I've already looked at the sources, but I'm unsure how to do it without causing trouble (deadlocks or access violations).

Thanks for any help :)

**Comment by renancostab** [comment]
Hi Piula,

This sounds fair, I'll update the version this weekend. 

The procedure OnTerminateWorker will be a callback and injected on each worker at the creation, so it will be triggered for each .terminate considering the thread worker context.

Any thoughts?

**Comment by piula** [comment]
Sounds promising.

In the meantime I have created a workaround: In hpthread.pas, I have introduced ``THPThreadClass = class of THPThread;``, and in hpthreadpool.pas I have changed:

```
42d41
<     FThreadClass: THPThreadClass;
65d62
<     property ThreadClass: THPThreadClass read FThreadClass write FThreadClass;
173c171
<     FWorkers.Add(FThreadClass.Create(FWorkEngine, @FRunning, @FWaiting));
---
>     FWorkers.Add(THPThread.Create(FWorkEngine, @FRunning, @FWaiting));
178d175
<   FThreadClass := THPThread;
```

This way I am able to specify a custom thread class in which I can easily do the required cleanup work. Maybe you might want to consider this enhancement as well. It doesn't break compatibility because by default all threads are created of type "THPThread" as before.

**Comment by renancostab** [comment]
NP

I'll add it

**Comment by renancostab** [comment]
Hi Piula

Those are the new properties on the THPThreadPool

    property OnTerminateWorker: TNotifyEvent read FNotify write SetNotify; // Event of terminate procedure (ASender: TObject)
    property UseSyncTerminate: Boolean read FSyncTerminate write SetSyncTerminate; // If True it will use Synchronize, if false it will be async and will run on the thread context
    property ThreadClass: THPThreadClass read FThreadClass write SetThreadClass;  // The class that allows the customization as you suggested

**Comment by piula** [comment]
Looks great 👍 I will try it the next days :)

**Comment by renancostab** [comment]
I'm closing this issue.
